robot_dimensions:
  # all in meters
  wheel_radius: 0.03
  track_width: 0.075
  # robot dimensions: 8cm x 8cm x 8cm
  length: 0.08
  width: 0.08
  height: 0.08
  # max velocity limits (m/s)
  max_velocity_sim: 1.5
  max_velocity_hw: 0.34

# System Execution Mode: "sim" for simulator (FIRASim), "hw" for physical robot hardware, "both" for both simulator and physical robot
mode: "sim"


field_dimensions:
  # all in meters
  play_area_length: 1.50
  play_area_width: 1.30
  wall_height: 0.05
  wall_thickness: 0.02
  goal_depth: 0.10
  goal_width: 0.40
  center_circle_radius: 0.20
  penalty_area_length: 0.15
  penalty_area_width: 0.70
  corner_triangle_size: 0.07


firasim:
  # read protobuf from simulator
  read_ip: 224.0.0.1
  read_port: 10002
  # send commands to simulator
  send_ip: 127.0.0.1
  send_port: 20011

hardware:
  bridge_mac: "00:70:07:25:C3:B8"
  robots:
    - id: 0
      mac: "98:3D:AE:B4:B6:44"

